version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:737719307477:task-definition/cdksoecscodedeploystackcodeDeployTaskDefEFBE3067:2"
        LoadBalancerInfo:
          ContainerName: "amazonSample"
          ContainerPort: 80
